services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE kvtest;'

language: java
jdk:
  - openjdk8
  - openjdk11

cache:
  directories:
    - "$HOME/.m2/repository"

script: mvn clean package -DtrimStackTrace=false -DuseFile=false

after_success:
  - mvn clean test jacoco:report coveralls:report
